#!/usr/bin/python

import socket

FILENAME = '/etc/resolv.conf'
OPENDNS = 'nameserver 208.67.222.222'
OPENDNS2 = 'nameserver 208.67.220.220'
LEVEL3 = 'nameserver 209.244.0.3'
VERISIGN = 'nameserver 64.6.64.6'
GOOGLE = 'nameserver 8.8.8.8'
REMOTE_SERVER = 'www.google.com'
def is_connected():
    try:
        host = socket.gethostbyname(REMOTE_SERVER)
        s = socket.create_connection((host,80),2)
        return True
    except:
        pass

    return False

if is_connected() == True:
    refile = open(FILENAME,'w')
    refile.write(OPENDNS)
    refile.close()
